name: Publish Docker Image - bun-debian

on:
  push:
    tags:
      - '@tpl/bun-debian@*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Bun version to publish'
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bun

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version
        id: version
        run: |
          # Simplified version extraction
          echo "version=${GITHUB_REF_NAME#@tpl/bun-debian@}" >> $GITHUB_OUTPUT
          echo "::notice::Extracted version: ${GITHUB_REF_NAME#@tpl/bun-debian@}"

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.version.outputs.version }}
            type=raw,value=latest
          labels: |
            org.opencontainers.image.title=Bun on Debian
            org.opencontainers.image.description=Bun v${{ steps.version.outputs.version }} runtime on Debian
            org.opencontainers.image.version=${{ steps.version.outputs.version }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./images/bun-debian
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
