name: Publish Bun Debian Docker image

on:
  release:
    types: [published]
  push:
    branches: [main]
    paths:
      - 'images/bun-debian/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/bun-debian
          flavor: |
            latest=false
          tags: |
            type=raw,value=1.2.5-debian
            type=raw,value=1.2-debian
            type=raw,value=1-debian
            type=raw,value=latest
          labels: |
            org.opencontainers.image.title=Bun Debian
            org.opencontainers.image.description=Bun v1.2.5 runtime on Debian with development tools
            org.opencontainers.image.version=1.2.5-debian

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./images/bun-debian
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}