name: Publish Docker Image - bun-debian

on:
  push:
    tags:
      - '@tpl/bun@*'

env:
  REGISTRY: ghcr.io

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version
        id: version
        run: |
          TAG=${{ github.ref_name }}
          # Extract version using regex pattern matching
          if [[ $TAG =~ @tpl/bun@([0-9]+\.[0-9]+\.[0-9]+.*)$ ]]; then
            VERSION="${BASH_REMATCH[1]}"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "::notice::Successfully extracted version: $VERSION"
          else
            echo "::error::Failed to extract version from tag: $TAG"
            exit 1
          fi
          echo "::notice::Extracted version: $VERSION"

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/bun
          tags: |
            type=raw,value=${{ steps.version.outputs.version }}
            type=raw,value=latest
          labels: |
            org.opencontainers.image.title=Bun on Debian
            org.opencontainers.image.description=Bun v${{ steps.version.outputs.version }} runtime on Debian
            org.opencontainers.image.version=${{ steps.version.outputs.version }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./images/bun-debian
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
